export const logRedactPaths = [
  'password',
  'currentPassword',
  'newPassword',
  'current_password',
  'new_password',
  'refreshToken',
  'refresh_token',
  'resetToken',
  'accessToken',
  'access_token',
  'authorization',
  'cookie',
  'passwordHash',
  'password_hash',
  'token',
  'database.password',
  '*.password',
  '*.currentPassword',
  '*.newPassword',
  '*.secret',
  '*.token',
  '*.accessToken',
  '*.refreshToken',
  '*.resetToken',
  '*.passwordHash',
  '*.secretKey',
  '*.accessKey',
  '*.authorization',
  '*.cookie',
  'req.headers.authorization',
  'req.headers.cookie',
  'MINIO_SECRET_KEY',
  'MINIO_ACCESS_KEY',
  'DATABASE_PASSWORD',
  'AUTH_TOKEN_SECRET',
  'auth.tokenSecret',
] as const;

export const logRedactCensor = '[Redacted]';
